In [2]:
import pandas as pd 
df=pd.read_csv('D:\Internships\IITK Oswald sir\IVF\Codes\Dataset\cleaned.csv')
df.info()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805069 entries, 0 to 805068
Data columns (total 56 columns):
 #   Column                                                          Non-Null Count   Dtype
---  ------                                                          --------------   -----
 0   Unnamed: 0                                                      805069 non-null  int64
 1   Patient Age at Treatment                                        805069 non-null  int64
 2   Total Number of Previous cycles, Both IVF and DI                805069 non-null  int64
 3   Total Number of Previous treatments, Both IVF and DI at clinic  805069 non-null  int64
 4   Total Number of Previous IVF cycles                             805069 non-null  int64
 5   Total Number of Previous DI cycles                              805069 non-null  int64
 6   Total number of previous pregnancies, Both IVF and DI           805069 non-null  int64
 7   Total number of IVF pregnancies                                 805069 non-null  int64
 8   Total number of DI pregnancies                                  805069 non-null  int64
 9   Total number of live births - conceived through IVF or DI       805069 non-null  int64
 10  Total number of live births - conceived through IVF             805069 non-null  int64
 11  Total number of live births - conceived through DI              805069 non-null  int64
 12  Type of Infertility - Female Primary                            805069 non-null  int64
 13  Type of Infertility - Female Secondary                          805069 non-null  int64
 14  Type of Infertility - Male Primary                              805069 non-null  int64
 15  Type of Infertility - Male Secondary                            805069 non-null  int64
 16  Type of Infertility -Couple Primary                             805069 non-null  int64
 17  Type of Infertility -Couple Secondary                           805069 non-null  int64
 18  Cause  of Infertility - Tubal disease                           805069 non-null  int64
 19  Cause of Infertility - Ovulatory Disorder                       805069 non-null  int64
 20  Cause of Infertility - Male Factor                              805069 non-null  int64
 21  Cause of Infertility - Patient Unexplained                      805069 non-null  int64
 22  Cause of Infertility - Endometriosis                            805069 non-null  int64
 23  Cause of Infertility - Cervical factors                         805069 non-null  int64
 24  Cause of Infertility - Female Factors                           805069 non-null  int64
 25  Cause of Infertility - Partner Sperm Concentration              805069 non-null  int64
 26  Cause of Infertility -  Partner Sperm Morphology                805069 non-null  int64
 27  Causes of Infertility - Partner Sperm Motility                  805069 non-null  int64
 28  Cause of Infertility -  Partner Sperm Immunological factors     805069 non-null  int64
 29  Stimulation used                                                805069 non-null  int64
 30  Type of treatment - IVF or DI                                   805069 non-null  int64
 31  Specific treatment type                                         805069 non-null  int64
 32  PGD                                                             805069 non-null  int64
 33  Elective Single Embryo Transfer                                 805069 non-null  int64
 34  Egg Source                                                      805069 non-null  int64
 35  Sperm From                                                      805069 non-null  int64
 36  Fresh Cycle                                                     805069 non-null  int64
 37  Frozen Cycle                                                    805069 non-null  int64
 38  Eggs Thawed                                                     805069 non-null  int64
 39  Fresh Eggs Collected                                            805069 non-null  int64
 40  Fresh Eggs Stored                                               805069 non-null  int64
 41  Total Eggs Mixed                                                805069 non-null  int64
 42  Eggs Mixed With Partner Sperm                                   805069 non-null  int64
 43  Eggs Mixed With Donor sperm                                     805069 non-null  int64
 44  Total Embryos Created                                           805069 non-null  int64
 45  Eggs Micro-injected                                             805069 non-null  int64
 46  Embryos from Eggs Micro-injected                                805069 non-null  int64
 47  Total Embryos Thawed                                            805069 non-null  int64
 48  Embryos Transfered                                              805069 non-null  int64
 49  Embryos Transfered from Eggs Micro-injected                     805069 non-null  int64
 50  Embryos Stored For Use By Patient                               805069 non-null  int64
 51  Embryos (from Eggs Micro-injected) Stored For Use By Patient    805069 non-null  int64
 52  Year of Treatment                                               805069 non-null  int64
 53  Live Birth Occurrence                                           805069 non-null  int64
 54  Number of Live Births                                           805069 non-null  int64
 55  Number of foetal sacs with fetal pulsation                      805069 non-null  int64
dtypes: int64(56)
memory usage: 344.0 MB

In [16]:
df

,Unnamed: 0,Patient Age at Treatment,"Total Number of Previous cycles, Both IVF and DI","Total Number of Previous treatments, Both IVF and DI at clinic",Total Number of Previous IVF cycles,Total Number of Previous DI cycles,"Total number of previous pregnancies, Both IVF and DI",Total number of IVF pregnancies,Total number of DI pregnancies,Total number of live births - conceived through IVF or DI,...,Embryos from Eggs Micro-injected,Total Embryos Thawed,Embryos Transfered,Embryos Transfered from Eggs Micro-injected,Embryos Stored For Use By Patient,Embryos (from Eggs Micro-injected) Stored For Use By Patient,Year of Treatment,Live Birth Occurrence,Number of Live Births,Number of foetal sacs with fetal pulsation
0,0,0,1,1,1,0,0,0,0,0,...,0,2,2,0,0,0,2,0,0,0
1,1,0,1,0,1,0,1,1,0,1,...,0,3,1,1,0,0,4,0,0,0
2,2,1,2,2,2,0,0,0,0,0,...,3,0,2,2,0,0,4,0,0,0
3,3,1,2,0,2,0,0,0,0,0,...,7,0,2,1,12,0,4,1,1,1
4,4,1,3,0,3,0,0,0,0,0,...,8,0,2,2,23,23,4,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805064,805064,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,15,1,1,1
805065,805065,0,1,0,1,0,1,1,0,1,...,4,0,1,1,0,0,15,1,1,1
805066,805066,1,1,1,1,0,0,0,0,0,...,0,0,2,0,0,0,16,0,0,0
805067,805067,3,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,16,0,0,0
805068,805068,0,2,2,2,0,0,0,0,0,...,4,0,2,2,0,0,15,1,1,1

In [17]:
dfy = df['Live Birth Occurrence']
x = df.drop('Live Birth Occurrence', axis='columns')

x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805069 entries, 0 to 805068
Data columns (total 55 columns):
 #   Column                                                          Non-Null Count   Dtype
---  ------                                                          --------------   -----
 0   Unnamed: 0                                                      805069 non-null  int64
 1   Patient Age at Treatment                                        805069 non-null  int64
 2   Total Number of Previous cycles, Both IVF and DI                805069 non-null  int64
 3   Total Number of Previous treatments, Both IVF and DI at clinic  805069 non-null  int64
 4   Total Number of Previous IVF cycles                             805069 non-null  int64
 5   Total Number of Previous DI cycles                              805069 non-null  int64
 6   Total number of previous pregnancies, Both IVF and DI           805069 non-null  int64
 7   Total number of IVF pregnancies                                 805069 non-null  int64
 8   Total number of DI pregnancies                                  805069 non-null  int64
 9   Total number of live births - conceived through IVF or DI       805069 non-null  int64
 10  Total number of live births - conceived through IVF             805069 non-null  int64
 11  Total number of live births - conceived through DI              805069 non-null  int64
 12  Type of Infertility - Female Primary                            805069 non-null  int64
 13  Type of Infertility - Female Secondary                          805069 non-null  int64
 14  Type of Infertility - Male Primary                              805069 non-null  int64
 15  Type of Infertility - Male Secondary                            805069 non-null  int64
 16  Type of Infertility -Couple Primary                             805069 non-null  int64
 17  Type of Infertility -Couple Secondary                           805069 non-null  int64
 18  Cause  of Infertility - Tubal disease                           805069 non-null  int64
 19  Cause of Infertility - Ovulatory Disorder                       805069 non-null  int64
 20  Cause of Infertility - Male Factor                              805069 non-null  int64
 21  Cause of Infertility - Patient Unexplained                      805069 non-null  int64
 22  Cause of Infertility - Endometriosis                            805069 non-null  int64
 23  Cause of Infertility - Cervical factors                         805069 non-null  int64
 24  Cause of Infertility - Female Factors                           805069 non-null  int64
 25  Cause of Infertility - Partner Sperm Concentration              805069 non-null  int64
 26  Cause of Infertility -  Partner Sperm Morphology                805069 non-null  int64
 27  Causes of Infertility - Partner Sperm Motility                  805069 non-null  int64
 28  Cause of Infertility -  Partner Sperm Immunological factors     805069 non-null  int64
 29  Stimulation used                                                805069 non-null  int64
 30  Type of treatment - IVF or DI                                   805069 non-null  int64
 31  Specific treatment type                                         805069 non-null  int64
 32  PGD                                                             805069 non-null  int64
 33  Elective Single Embryo Transfer                                 805069 non-null  int64
 34  Egg Source                                                      805069 non-null  int64
 35  Sperm From                                                      805069 non-null  int64
 36  Fresh Cycle                                                     805069 non-null  int64
 37  Frozen Cycle                                                    805069 non-null  int64
 38  Eggs Thawed                                                     805069 non-null  int64
 39  Fresh Eggs Collected                                            805069 non-null  int64
 40  Fresh Eggs Stored                                               805069 non-null  int64
 41  Total Eggs Mixed                                                805069 non-null  int64
 42  Eggs Mixed With Partner Sperm                                   805069 non-null  int64
 43  Eggs Mixed With Donor sperm                                     805069 non-null  int64
 44  Total Embryos Created                                           805069 non-null  int64
 45  Eggs Micro-injected                                             805069 non-null  int64
 46  Embryos from Eggs Micro-injected                                805069 non-null  int64
 47  Total Embryos Thawed                                            805069 non-null  int64
 48  Embryos Transfered                                              805069 non-null  int64
 49  Embryos Transfered from Eggs Micro-injected                     805069 non-null  int64
 50  Embryos Stored For Use By Patient                               805069 non-null  int64
 51  Embryos (from Eggs Micro-injected) Stored For Use By Patient    805069 non-null  int64
 52  Year of Treatment                                               805069 non-null  int64
 53  Number of Live Births                                           805069 non-null  int64
 54  Number of foetal sacs with fetal pulsation                      805069 non-null  int64
dtypes: int64(55)
memory usage: 337.8 MB

In [18]:
dfx = scaler.fit_transform(x)
dfx
dfy

0         0
1         0
2         0
3         1
4         1
         ..
805064    1
805065    1
805066    0
805067    0
805068    1
Name: Live Birth Occurrence, Length: 805069, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(dfx, dfy, test_size=0.25)

In [20]:
model = DecisionTreeClassifier()
params = {
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [1, 10, 100, 1000]
}

clf = GridSearchCV(
    estimator=model, 
    param_grid=params, 
    cv=10,  # 10-fold cross validation
    n_jobs=-1  # run in parallel
)
clf.fit(X_train, y_train)

cv_results = pd.DataFrame(clf.cv_results_)

In [21]:
cv_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_splitter,params,split0_test_score,split1_test_score,...,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,5.038076,0.733235,0.044018,0.012052,gini,1,best,"{'criterion': 'gini', 'max_depth': 1, 'splitte...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
1,4.721430,0.723184,0.048233,0.012104,gini,1,random,"{'criterion': 'gini', 'max_depth': 1, 'splitte...",1.000000,0.76686,...,0.766860,1.000000,0.766843,0.814641,0.814624,0.766843,0.766843,0.827915,0.08853,15
2,4.111795,0.256026,0.047082,0.006215,gini,10,best,"{'criterion': 'gini', 'max_depth': 10, 'splitt...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
3,8.483659,2.291340,0.040904,0.004190,gini,10,random,"{'criterion': 'gini', 'max_depth': 10, 'splitt...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
4,3.827384,0.237564,0.043921,0.006883,gini,100,best,"{'criterion': 'gini', 'max_depth': 100, 'split...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
5,6.969831,2.615069,0.038809,0.004142,gini,100,random,"{'criterion': 'gini', 'max_depth': 100, 'split...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
6,3.841280,0.212150,0.037945,0.003888,gini,1000,best,"{'criterion': 'gini', 'max_depth': 1000, 'spli...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
7,8.913506,3.866491,0.048485,0.007068,gini,1000,random,"{'criterion': 'gini', 'max_depth': 1000, 'spli...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
8,3.831067,0.244089,0.043573,0.010922,entropy,1,best,"{'criterion': 'entropy', 'max_depth': 1, 'spli...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
9,3.861907,0.216731,0.040912,0.005808,entropy,1,random,"{'criterion': 'entropy', 'max_depth': 1, 'spli...",0.766847,1.00000,...,0.812057,0.811146,0.766843,0.766843,0.810715,0.766843,0.810914,0.807907,0.06736,16
10,3.964871,0.201801,0.045116,0.008693,entropy,10,best,"{'criterion': 'entropy', 'max_depth': 10, 'spl...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
11,8.132334,3.950876,0.041798,0.005558,entropy,10,random,"{'criterion': 'entropy', 'max_depth': 10, 'spl...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
12,3.811261,0.284476,0.038067,0.004696,entropy,100,best,"{'criterion': 'entropy', 'max_depth': 100, 'sp...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
13,5.981005,2.337437,0.039241,0.006091,entropy,100,random,"{'criterion': 'entropy', 'max_depth': 100, 'sp...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
14,3.832758,0.237415,0.038668,0.008475,entropy,1000,best,"{'criterion': 'entropy', 'max_depth': 1000, 's...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1
15,5.246446,1.265319,0.020324,0.004465,entropy,1000,random,"{'criterion': 'entropy', 'max_depth': 1000, 's...",1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,1

In [22]:
cv_results = cv_results[['mean_test_score', 'param_criterion', 'param_splitter', 'param_max_depth']]
cv_results.sort_values(by='mean_test_score', ascending=False)

    mean_test_score param_criterion param_splitter param_max_depth
0          1.000000            gini           best               1
2          1.000000            gini           best              10
3          1.000000            gini         random              10
4          1.000000            gini           best             100
5          1.000000            gini         random             100
6          1.000000            gini           best            1000
7          1.000000            gini         random            1000
8          1.000000         entropy           best               1
10         1.000000         entropy           best              10
11         1.000000         entropy         random              10
12         1.000000         entropy           best             100
13         1.000000         entropy         random             100
14         1.000000         entropy           best            1000
15         1.000000         entropy         random            1000
1          0.827915            gini         random               1
9          0.807907         entropy         random               1